services:
  - type: web
    name: homeopathway-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: MONGODB_URI
        value: "mongodb+srv://sanaulla7676:Suhail%4008@cluster0.pzskqem.mongodb.net/mefy_production?appName=Cluster0"
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
