/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "background": "hsl(var(--background))",
            "foreground": "hsl(var(--foreground))",
            "card": "hsl(var(--card))",
            "card-foreground": "hsl(var(--card-foreground))",
            "popover": "hsl(var(--popover))",
            "popover-foreground": "hsl(var(--popover-foreground))",
            "primary": "hsl(var(--primary))",
            "primary-foreground": "hsl(var(--primary-foreground))",
            "secondary": "hsl(var(--secondary))",
            "secondary-foreground": "hsl(var(--secondary-foreground))",
            "muted": "hsl(var(--muted))",
            "muted-foreground": "hsl(var(--muted-foreground))",
            "accent": "hsl(var(--accent))",
            "accent-foreground": "hsl(var(--accent-foreground))",
            "destructive": "hsl(var(--destructive))",
            "destructive-foreground": "hsl(var(--destructive-foreground))",
            "border": "hsl(var(--border))",
            "input": "hsl(var(--input))",
            "ring": "hsl(var(--ring))",
            "sidebar": "hsl(var(--sidebar))",
            "sidebar-border": "hsl(var(--sidebar-border))",
            
            // Legacy colors (kept for compatibility)
            "on-tertiary-container": "#2180ff",
            "on-tertiary": "#ffffff",
            "on-surface-variant": "#44474e",
            "on-secondary-fixed-variant": "#434750",
            "on-secondary-container": "#61646e",
            "surface-container-lowest": "#ffffff",
            "surface-dim": "#dbdad6",
            "on-tertiary-fixed": "#001a41",
            "outline-variant": "#c4c6cf",
            "primary-fixed-dim": "#b2c7f3",
            "deep-navy": "#001A3D",
            "error-container": "#ffdad6",
            "surface-variant": "#e4e2de",
            "tertiary-fixed-dim": "#adc7ff",
            "matte-black": "#1A1A1A",
            "secondary-fixed-dim": "#c4c6d2",
            "lavender-mist": "#E8EAF6",
            "inverse-on-surface": "#f2f0ed",
            "tertiary-fixed": "#d8e2ff",
            "surface-bright": "#fbf9f5",
            "on-secondary-fixed": "#181b24",
            "on-error": "#ffffff",
            "inverse-primary": "#b2c7f3",
            "on-primary-container": "#6f84ad",
            "electric-blue": "#007BFF",
            "on-secondary": "#ffffff",
            "primary-fixed": "#d7e3ff",
            "surface-container-high": "#eae8e4",
            "on-tertiary-fixed-variant": "#004493",
            "surface-tint": "#4a5f85",
            "secondary-container": "#e0e2ee",
            "inverse-surface": "#30312e",
            "cta-pink": "#FF2D78",
            "surface-container": "#efeeea",
            "on-surface": "#1b1c1a",
            "surface": "#fbf9f5",
            "surface-container-low": "#f5f3ef",
            "tertiary": "#000000",
            "secondary-fixed": "#e0e2ee",
            "surface-container-highest": "#e4e2de",
            "cream-white": "#FDFBF7",
            "error": "#ba1a1a",
            "on-background": "#1b1c1a",
            "outline": "#74777f",
            "on-primary-fixed": "#011b3e",
            "on-primary-fixed-variant": "#32476c",
            "tertiary-container": "#001a41",
            "on-error-container": "#93000a",
            "on-primary": "#ffffff",
            "primary-container": "#011b3e"
        },
        "borderRadius": {
            "DEFAULT": "1rem",
            "lg": "2rem",
            "xl": "3rem",
            "full": "9999px"
        },
        "spacing": {
            "container-padding-mobile": "24px",
            "container-padding-desktop": "64px",
            "base": "8px",
            "gutter": "24px",
            "section-gap": "120px"
        },
        "fontFamily": {
            "body-lg": ["Manrope", "sans-serif"],
            "label-md": ["Inter", "sans-serif"],
            "label-sm": ["Inter", "sans-serif"],
            "headline-lg-mobile": ["Manrope", "sans-serif"],
            "headline-lg": ["Manrope", "sans-serif"],
            "headline-md": ["Manrope", "sans-serif"],
            "headline-display": ["Manrope", "sans-serif"],
            "body-md": ["Manrope", "sans-serif"]
        },
        "fontSize": {
            "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "300" }],
            "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
            "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600" }],
            "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "300" }],
            "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "300" }],
            "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "400" }],
            "headline-display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "200" }],
            "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
        }
    }
  },
  plugins: [],
}
